sudo: required
services:
- docker
language: node_js
node_js:
- "9"
script:
- npm install
- npm run build
after_success:
- docker build -t quorauk/challongelive .
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push quorauk/challongelive
