version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
  challonge:
    image: quorauk/challongelive:latest
    ports:
      - "80:80"
