version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/c/Users/maxpr/Documents/challongelive/nginx:/etc/nginx/conf.d"
      - "/c/Users/maxpr/Documents/challongelive/dist:/var/www/vue"
